namespace: pan_community

name: skillet

version: 1.0.6

readme: README.md

authors:
  - Nathan Embery <nembery@paloaltonetworks.com>
  - Andrew Mallory <amallory@paloaltonetworks.com>
  - Anna Barone <abarone@paloaltonetworks.com>


description: Collection for working with PAN-OS Configuration XML Snippets and Skillets

license_file: 'LICENSE'

tags:
  - networking
  - paloaltonetworks
  - panw
  - security
  - panos

dependencies: {
  'paloaltonetworks.panos': '*'
}

repository: https://github.com/PaloAltoNetworks/skillet_ansible

homepage: https://github.com/PaloAltoNetworks/skillet_ansible

issues: https://github.com/PaloAltoNetworks/skillet_ansible/issues
